
// src/models/User.model.ts
import { DataTypes, Model, type Sequelize, type ModelCtor, type Optional } from 'sequelize';
import bcrypt from 'bcryptjs';

// Attributes for creating a User
export interface UserAttributes {
  id?: string; // UUID, can be generated by DB or Sequelize
  email: string;
  password_hash: string; // Will store the plain password initially, hook will hash it
  username?: string | null;
  avatar_url?: string | null;
  bio?: string | null;
  wallet_address?: string | null;
  role?: 'user' | 'admin';
  createdAt?: Date;
  updatedAt?: Date;
}

// Attributes of a User instance (includes all UserAttributes and methods)
export interface UserInstance extends Model<UserAttributes, Optional<UserAttributes, 'id' | 'role' | 'createdAt' | 'updatedAt'>>, UserAttributes {
  isValidPassword(password: string): Promise<boolean>;
  // Define associations here if needed, e.g., getCreatedNfts: HasManyGetAssociationsMixin<NFTInstance>;
}

export default (sequelize: Sequelize): ModelCtor<UserInstance> => {
  const User = sequelize.define<UserInstance>('User', {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
      allowNull: false,
    },
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true,
      validate: {
        isEmail: true,
      },
    },
    password_hash: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    username: {
      type: DataTypes.STRING,
      unique: true,
      allowNull: true,
    },
    avatar_url: {
      type: DataTypes.STRING,
      allowNull: true,
      validate: {
        isUrl: true,
      },
    },
    bio: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    wallet_address: {
      type: DataTypes.STRING,
      unique: true,
      allowNull: true,
    },
    role: {
      type: DataTypes.ENUM('user', 'admin'),
      defaultValue: 'user',
      allowNull: false,
    }
  }, {
    tableName: 'users',
    timestamps: true,
    underscored: true,
    hooks: {
      beforeCreate: async (user: UserInstance) => {
        if (user.password_hash && !user.password_hash.startsWith('$2a$') && !user.password_hash.startsWith('$2b$')) {
          const salt = await bcrypt.genSalt(10);
          user.password_hash = await bcrypt.hash(user.password_hash, salt);
        }
      },
      beforeUpdate: async (user: UserInstance) => {
        if (user.changed('password_hash') && user.password_hash && !user.password_hash.startsWith('$2a$') && !user.password_hash.startsWith('$2b$')) {
          const salt = await bcrypt.genSalt(10);
          user.password_hash = await bcrypt.hash(user.password_hash, salt);
        }
      }
    }
  });

  // Instance method
  User.prototype.isValidPassword = async function(password: string): Promise<boolean> {
    return bcrypt.compare(password, this.password_hash);
  };

  // Static method (though not typically used this way with instance methods available)
  // User.hashPassword = async function(password: string): Promise<string> {
  //   const salt = await bcrypt.genSalt(10);
  //   return bcrypt.hash(password, salt);
  // };
  
  // Define associations within a static associate method or after all models are defined
  // User.associate = (models) => {
  //   User.hasMany(models.NFT, { as: 'createdNfts', foreignKey: 'creator_id' });
  //   User.hasMany(models.NFT, { as: 'ownedNfts', foreignKey: 'owner_id' });
  // };

  return User;
};
