
// src/models/User.model.ts
import { DataTypes, Model, type Sequelize, type ModelCtor, type Optional, type HasManyGetAssociationsMixin, type HasManyAddAssociationMixin, type HasManyCreateAssociationMixin } from 'sequelize';
import bcrypt from 'bcryptjs';
import type { NFTInstance } from './NFT.model'; // Assuming NFTInstance will be defined

// Attributes for creating a User
export interface UserAttributes {
  id?: string; // UUID, can be generated by DB or Sequelize
  email: string;
  password_hash: string; // Will store the plain password initially, hook will hash it
  username?: string | null;
  avatar_url?: string | null;
  bio?: string | null;
  wallet_address?: string | null;
  role?: 'user' | 'admin';
  createdAt?: Date;
  updatedAt?: Date;
}

// Attributes of a User instance (includes all UserAttributes and methods)
export interface UserInstance extends Model<UserAttributes, Optional<UserAttributes, 'id' | 'role' | 'createdAt' | 'updatedAt'>>, UserAttributes {
  isValidPassword(password: string): Promise<boolean>;
  
  // Define association methods
  getCreatedNfts: HasManyGetAssociationsMixin<NFTInstance>;
  addCreatedNft: HasManyAddAssociationMixin<NFTInstance, string>; // string for NFT's PK (UUID)
  createCreatedNft: HasManyCreateAssociationMixin<NFTInstance>;

  getOwnedNfts: HasManyGetAssociationsMixin<NFTInstance>;
  addOwnedNft: HasManyAddAssociationMixin<NFTInstance, string>;
  createOwnedNft: HasManyCreateAssociationMixin<NFTInstance>;

  // Add other association mixins as needed for Bids, Favorites, Collections etc.
}

export default (sequelize: Sequelize): ModelCtor<UserInstance> => {
  const User = sequelize.define<UserInstance>('User', {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
      allowNull: false,
    },
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true,
      validate: {
        isEmail: true,
      },
    },
    password_hash: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    username: {
      type: DataTypes.STRING,
      unique: true,
      allowNull: true,
    },
    avatar_url: {
      type: DataTypes.STRING,
      allowNull: true,
      validate: {
        isUrl: true,
      },
    },
    bio: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    wallet_address: {
      type: DataTypes.STRING,
      unique: true,
      allowNull: true,
    },
    role: {
      type: DataTypes.ENUM('user', 'admin'),
      defaultValue: 'user',
      allowNull: false,
    }
  }, {
    tableName: 'users',
    timestamps: true,
    underscored: true,
    hooks: {
      beforeCreate: async (user: UserInstance) => {
        if (user.password_hash && !user.password_hash.startsWith('$2a$') && !user.password_hash.startsWith('$2b$')) {
          const salt = await bcrypt.genSalt(10);
          user.password_hash = await bcrypt.hash(user.password_hash, salt);
        }
      },
      beforeUpdate: async (user: UserInstance) => {
        if (user.changed('password_hash') && user.password_hash && !user.password_hash.startsWith('$2a$') && !user.password_hash.startsWith('$2b$')) {
          const salt = await bcrypt.genSalt(10);
          user.password_hash = await bcrypt.hash(user.password_hash, salt);
        }
      }
    }
  });

  // Instance method
  User.prototype.isValidPassword = async function(password: string): Promise<boolean> {
    return bcrypt.compare(password, this.password_hash);
  };
  
  // Static method for associations
  (User as any).associate = (models: any) => { // Use 'any' for models for simplicity in associate methods
    User.hasMany(models.NFT, { 
        as: 'createdNfts', 
        foreignKey: 'creator_id',
        onDelete: 'RESTRICT', // Prevent deleting user if they created NFTs
        onUpdate: 'CASCADE'
    });
    User.hasMany(models.NFT, { 
        as: 'ownedNfts', 
        foreignKey: 'owner_id',
        onDelete: 'SET NULL', // If user is deleted, their owned NFTs become ownerless (or handle differently)
        onUpdate: 'CASCADE'
    });
    // Add other associations like Bids, Favorites, Collections, Notifications, UserFollows here
    // e.g., User.hasMany(models.Collection, { foreignKey: 'user_id', as: 'collections' });
  };

  return User;
};
